package model;
// Generated 2021�~10��27�� �U��12:13:20 by Hibernate Tools 5.5.7.Final

import java.math.BigDecimal;

/**
 * Coffees generated by hbm2java
 */
public class Coffees implements java.io.Serializable
{

	private String cofName;
	private int supId;
	private BigDecimal price;
	private int sales;
	private int total;

	public Coffees()
	{
	}

	public Coffees(String cofName, int supId, BigDecimal price, int sales, int total)
	{
		this.cofName = cofName;
		this.supId = supId;
		this.price = price;
		this.sales = sales;
		this.total = total;
	}

	public String getCofName()
	{
		return this.cofName;
	}

	public void setCofName(String cofName)
	{
		this.cofName = cofName;
	}

	public int getSupId()
	{
		return this.supId;
	}

	public void setSupId(int supId)
	{
		this.supId = supId;
	}

	public BigDecimal getPrice()
	{
		return this.price;
	}

	public void setPrice(BigDecimal price)
	{
		this.price = price;
	}

	public int getSales()
	{
		return this.sales;
	}

	public void setSales(int sales)
	{
		this.sales = sales;
	}

	public int getTotal()
	{
		return this.total;
	}

	public void setTotal(int total)
	{
		this.total = total;
	}

	public String toString()
	{
		return cofName + ":" + price;
	}
}
