package MyMod;
// Generated 2021�~11��18�� �U��2:07:16 by Hibernate Tools 5.5.7.Final

/**
 * Eporderdt generated by hbm2java
 */
public class Eporderdt implements java.io.Serializable
{

	private EporderdtId id;
	private Eporder eporder;
	private Epproduct epproduct;
	private int amount;

	public Eporderdt()
	{
	}

	public Eporderdt(EporderdtId id, Eporder eporder, Epproduct epproduct, int amount)
	{
		this.id = id;
		this.eporder = eporder;
		this.epproduct = epproduct;
		this.amount = amount;
	}

	public EporderdtId getId()
	{
		return this.id;
	}

	public void setId(EporderdtId id)
	{
		this.id = id;
	}

	public Eporder getEporder()
	{
		return this.eporder;
	}

	public void setEporder(Eporder eporder)
	{
		this.eporder = eporder;
	}

	public Epproduct getEpproduct()
	{
		return this.epproduct;
	}

	public void setEpproduct(Epproduct epproduct)
	{
		this.epproduct = epproduct;
	}

	public int getAmount()
	{
		return this.amount;
	}

	public void setAmount(int amount)
	{
		this.amount = amount;
	}

}
